sudo: required

language: minimal

services:
  - docker

jobs:
  include:
    - stage: main
      name: RPMlint
      script: docker run --rm -ti -v `pwd`:/git quay.io/hairmare/fedora_rpmdev rpmlint ocaml-magic.spec
    - stage: main
      name: CentOS RPM
      script: docker run --rm -ti -v `pwd`:/git quay.io/hairmare/centos_rpmdev /git/.travis/rpm.sh
    - stage: main
      name: Fedora RPM
      script: docker run --rm -ti -v `pwd`:/git quay.io/hairmare/fedora_rpmdev /git/.travis/rpm.sh
